name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v5

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: cd backend && poetry install --no-root

      - name: Executar testes
        run: cd backend && poetry run task test